ATLANTA_BRAVES = "Atlanta Braves"
MIAMI_MARLINS = "Miami Marlins"
PHILADELPHIA_PHILLIES = "Philadelphia Phillies"
CHICAGO_CUBS = "Chicago Cubs"
PITTSBURGH_PIRATES = "Pittsburgh Pirates"
ARIZONA_DIAMONDBACKS = "Arizona Diamondbacks"
LOS_ANGELES_ANGELS = "Los Angeles Angels"
DETROIT_TIGERS = "Detroit Tigers"
TAMPA_BAY_RAYS = "Tampa Bay Rays"
CLEVELAND_GUARDIANS = "Cleveland Guardians"
SAN_FRANCISCO_GIANTS = "San Francisco Giants"
NEW_YORK_YANKEES = "New York Yankees"
COLORADO_ROCKIES = "Colorado Rockies"
TEXAS_RANGERS = "Texas Rangers"
BOSTON_RED_SOX = "Boston Red Sox"
CINCINNATI_REDS = "Cincinnati Reds"
ST_LOUIS_CARDINALS = "St Louis Cardinals"
LOS_ANGELES_DODGERS = "Los Angeles Dodgers"
MILWAUKEE_BREWERS = "Milwaukee Brewers"
BALTIMORE_ORIOLES = "Baltimore Orioles"
NEW_YORK_METS = "New York Mets"
WASHINGTON_NATIONALS = "Washington Nationals"
KANSAS_CITY_ROYALS = "Kansas City Royals"
MINNESOTA_TWINS = "Minnesota Twins"
HOUSTON_ASTROS = "Houston Astros"
OAKLAND_ATHLETICS = "Oakland Athletics"
SEATTLE_MARINERS = "Seattle Mariners"
CHICAGO_WHITE_SOX = "Chicago White Sox"
SAN_DIEGO_PADRES = "San Diego Padres"
TORONTO_BLUE_JAYS = "Toronto Blue Jays"

allRivalTeams = [
    ATLANTA_BRAVES,
    MIAMI_MARLINS,
    PHILADELPHIA_PHILLIES,
    CHICAGO_CUBS,
    PITTSBURGH_PIRATES,
    ARIZONA_DIAMONDBACKS,
    LOS_ANGELES_ANGELS,
    DETROIT_TIGERS,
    TAMPA_BAY_RAYS,
    CLEVELAND_GUARDIANS,
    SAN_FRANCISCO_GIANTS,
    NEW_YORK_YANKEES,
    COLORADO_ROCKIES,
    TEXAS_RANGERS,
    CINCINNATI_REDS,
    ST_LOUIS_CARDINALS,
    LOS_ANGELES_DODGERS,
    MILWAUKEE_BREWERS,
    BALTIMORE_ORIOLES,
    NEW_YORK_METS,
    WASHINGTON_NATIONALS,
    KANSAS_CITY_ROYALS,
    MINNESOTA_TWINS,
    HOUSTON_ASTROS,
    OAKLAND_ATHLETICS,
    SEATTLE_MARINERS,
    CHICAGO_WHITE_SOX,
    SAN_DIEGO_PADRES,
    TORONTO_BLUE_JAYS,
]
