teams = {
  'ATLANTA_BRAVES': 'atlanta_braves',
  'MIAMI_MARLINS': 'miami_marlins',
  'NEW_YORK_METS': 'new_york_mets',
  'PHILADELPHIA_PHILLIES': 'philadelphia_phillies',
  'WASHINGTON_NATIONALS': 'washington_nationals',
  'CHICAGO_CUBS': 'chicago_cubs',
  'CINCINNATI_REDS': 'cincinnati_reds',
  'MILWAUKEE_BREWERS': 'milwaukee_brewers',
  'PITTSBURGH_PIRATES': 'pittsburgh_pirates',
  'ST_LOUIS_CARDINALS': 'st_louis_cardinals',
  'ARIZONA_DIAMONDBACKS': 'arizona_diamondbacks',
  'COLORADO_ROCKIES': 'colorado_rockies',
  'LOS_ANGELES_DODGERS': 'los_angeles_dodgers',
  'SAN_DIEGO_PADRES': 'san_diego_padres',
  'SAN_FRANCISCO_GIANTS': 'san_francisco_giants',
  'BALTIMORE_ORIOLES': 'baltimore_orioles',
  'BOSTON_RED_SOX': 'boston_red_sox',
  'NEW_YORK_YANKEES': 'new_york_yankees',
  'TAMPA_BAY_RAYS': 'tampa_bay_rays',
  'TORONTO_BLUE_JAYS': 'toronto_blue_jays',
  'CHICAGO_WHITE_SOX': 'chicago_white_sox',
  'CLEVELAND_INDIANS': 'cleveland_indians',
  'DETROIT_TIGERS': 'detroit_tigers',
  'KANSAS_CITY_ROYALS': 'kansas_city_royals',
  'MINNESOTA_TWINS': 'minnesota_twins',
  'HOUSTON_ASTROS': 'houston_astros',
  'LOS_ANGELES_ANGELS': 'los_angeles_angels',
  'OAKLAND_ATHLETICS': 'oakland_athletics',
  'SEATTLE_MARINERS': 'seattle_mariners',
  'TEXAS_RANGERS': 'texas_rangers'
}

